version: '3.8'

services:

  backend:
    build: ./backend
    entrypoint: ./entrypoint.sh
    command: poetry run uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432


volumes:
  postgresdata:
