version: '3.9'

services:
  app:
    restart: unless-stopped
    volumes:
      - ./app/:/app/:cached
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    restart: unless-stopped
    ports:
      - 15239:5432


  redis:
    ports:
      - 6379:6379
