version: "3.9"

x-app_environment: &app_environment
  environment:
    - POSTGRES_PASSWORD
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER
    - POSTGRES_HOST

services:

  backend:
    build:
      context: backend
    <<: *app_environment

  db:
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER
