"""

Revision ID: 97fff2c09489
Revises: c19563c92cd6
Create Date: 2024-07-18 11:35:13.439943

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "97fff2c09489"
down_revision: Union[str, None] = "c19563c92cd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
