"""New Migration

Revision ID: 5978a2ef1413
Revises:
Create Date: 2024-04-03 21:03:04.382624

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "5978a2ef1413"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
